# Change these first
owner: joevaughan # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Joe Vaughan
    url: https://joevaughan.com
  - name: Dr Veoj
    url: https://dr.veoj.me
  - name: Snipz
    url: https://snipz.io
  - name: Pareto Principals Ltd
    url: https://paretoprincipals.co.uk
  - name: The Photography Waffle
    url: https://thephotographywaffle.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My site statuses
  introTitle: "**Status** The statuses of the websites I run"
  introMessage: These are the current statuses (and stats) for the sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
