owner: joevaughan
repo: upptime

assignees: 
  - joevaughan

sites:
  - name: joevaughan.com (my portfolio)
    url: https://joevaughan.com
  - name: snipz.io (snippet manager)
    url: https://snipz.io
  - name: paretoprincipals.co.uk (my company)
    url: https://paretoprincipals.co.uk
  - name: thephotographywaffle.com (my podcast)
    url: https://thephotographywaffle.com

status-website:

  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: light
  name:  Status
  #introTitle: "**Status** The statuses of the websites I run"
  introMessage: These are the current statuses (and stats) for the sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
